name: Deploy Angular App to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' # This should point to the folder where your Angular app is built
  AZURE_WEBAPP_NAME: Pluralsightfe

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build Angular app
        run: npm run build --prod
      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production' # Adjust if you're using deployment slots
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE2 }} # Make sure to set this secret in your repository settings
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/dist # Adjust if your Angular app's build output is in a different directory
